import { expect, test } from '@playwright/test';

import {
  addCard,
  cardIn,
  cardTitles,
  column,
  createBoard,
  handleFor,
  keyboardMove,
  openBoard,
  signIn,
} from '../fixtures/app';
import { ANA, BOARD, CARLA, SECOND_BOARD } from '../fixtures/seed-facts';

/**
 * The board as one person operates it: keyboard drag, WIP words, roles.
 *
 * The keyboard specs are not an accessibility footnote. Drag and drop is this
 * product's primary interaction, and a pointer-only implementation is a WCAG 2.1.1
 * failure on the thing the app is for -- so the keyboard path is a functional
 * requirement and is tested as one.
 */
test.describe('the board', () => {
  test.beforeEach(async ({ page }) => {
    await signIn(page, ANA.email);
    await openBoard(page);
  });

  test('renders every seeded column, in order', async ({ page }) => {
    for (const name of BOARD.lists) {
      await expect(column(page, name)).toBeVisible();
    }
  });

  test('states the WIP limit in words, not only in colour', async ({ page }) => {
    // The measurement behind this rule is in `apps/web/lib/contrast.test.ts`: the
    // three WIP inks separate by 1.23:1 in greyscale in light and 1.02:1 in dark,
    // which is to say not at all. The words are the signal, not a caption on it.
    const chip = column(page, 'In progress').getByLabel(/Work in progress/);
    await expect(chip).toBeVisible();
    await expect(chip).toHaveText(/\d+\/\d+|\d+ cards|At limit|Over limit/);
  });

  test('moves a card with the keyboard alone, and it reaches the database', async ({ page }) => {
    // Its own two-column board. "One column to the right" has to mean something
    // fixed, and the seeded board gains columns as other specs add them -- so a
    // move that lands in `Done` when this file runs alone lands elsewhere when
    // the whole suite does.
    await createBoard(page, `Keyboard ${Date.now()}`, ['From', 'To']);
    const card = await addCard(page, 'From', 'Moved by keyboard');
    const before = await cardTitles(page, 'To');

    await keyboardMove(page, handleFor(page, 'From', card), 'ArrowRight');

    await expect(cardIn(page, 'To', card)).toBeVisible();
    expect(await cardTitles(page, 'To')).toHaveLength(before.length + 1);

    // The optimistic update draws the card in its new column before any round
    // trip. Reloading is what separates "the browser moved it" from "the server
    // agreed": a move that only ever existed in React state comes back where it
    // started.
    await page.reload();
    await expect(page.getByText('Live', { exact: true })).toBeVisible({ timeout: 20_000 });
    await expect(cardIn(page, 'To', card)).toBeVisible();
  });

  test('adds, renames and archives a card', async ({ page }) => {
    const title = await addCard(page, 'Backlog', `Round trip ${Date.now()}`);
    const renamed = `${title} renamed`;

    await cardIn(page, 'Backlog', title).click();
    await page.getByLabel(`Rename ${title}`).fill(renamed);
    await page.getByRole('button', { name: 'Save' }).click();
    await expect(cardIn(page, 'Backlog', renamed)).toBeVisible();

    await cardIn(page, 'Backlog', renamed).click();
    // Named, because a board has one "Archive" per column plus this one and a
    // bare name resolves to five elements. That ambiguity is a real finding --
    // a screen reader reading the page out of order hears the same word five
    // times -- which is why the fix was in the component, not in this locator.
    await page.getByRole('button', { name: `Archive ${renamed}` }).click();
    await expect(cardIn(page, 'Backlog', renamed)).toHaveCount(0);
  });

  test('adds a list, and it takes a position rather than appearing anywhere', async ({ page }) => {
    const name = `Column ${Date.now()}`;
    await page.getByRole('button', { name: /Add a list/ }).click();
    await page.getByLabel('Name of the new list').fill(name);
    await page.getByRole('button', { name: 'Add list' }).click();

    await expect(column(page, name)).toBeVisible();

    // At the end, because that is where a new column goes and the position is
    // generated by `keyBetween(last, null)`.
    const headings = await page.locator('.column-name').allTextContents();
    expect(headings.at(-1)?.trim()).toBe(name);
  });

  test('escape closes an inline form without saving', async ({ page }) => {
    await column(page, 'Backlog')
      .getByRole('button', { name: /Add a card to Backlog/ })
      .click();
    const field = page.getByLabel(/Title of the new card in Backlog/);
    await field.fill('Never saved');
    await page.keyboard.press('Escape');

    await expect(field).toHaveCount(0);
    await expect(cardIn(page, 'Backlog', 'Never saved')).toHaveCount(0);
    // Focus goes back to the button it came from, rather than to `<body>`, so the
    // next Tab continues from where the person was.
    await expect(
      column(page, 'Backlog').getByRole('button', { name: /Add a card to Backlog/ }),
    ).toBeFocused();
  });

  test('shows only the boards this person is a member of', async ({ page }) => {
    await page.goto('/boards');
    await expect(page.getByRole('link', { name: new RegExp(BOARD.name) })).toBeVisible();
    await expect(page.getByRole('link', { name: new RegExp(SECOND_BOARD.name) })).toBeVisible();
  });
});

test.describe('a viewer', () => {
  test('cannot move, add or archive anything', async ({ page }) => {
    // Carla is seeded as a VIEWER on this board. The controls are absent rather
    // than disabled: a disabled button implies a permission she might acquire,
    // and the matrix in `packages/shared/src/roles.ts` says she may not.
    await signIn(page, CARLA.email);
    await openBoard(page);

    await expect(page.getByRole('button', { name: /^Move / })).toHaveCount(0);
    await expect(page.getByRole('button', { name: /Add a card to/ })).toHaveCount(0);
    await expect(page.getByRole('button', { name: /Add a list/ })).toHaveCount(0);

    // And she can still read it, which is the point of the role. Asserted against
    // a column rather than a named card, because no spec should depend on where
    // an earlier one left a seeded card.
    await expect(column(page, 'In progress')).toBeVisible();
    await expect(page.locator('.card-title').first()).toBeVisible();
  });

  test('cannot manage members', async ({ page }) => {
    await signIn(page, CARLA.email);
    await openBoard(page);

    // The roster is visible -- knowing who is on a board is part of reading it --
    // but the controls that change it are not rendered.
    await expect(page.getByRole('heading', { name: 'Members' })).toBeVisible();
    await expect(page.getByLabel('Add someone by email')).toHaveCount(0);
    await expect(page.getByRole('button', { name: /^Remove/ })).toHaveCount(0);
  });
});
