import { SERVER_EVENTS, type Board, type CardMoved } from '@kan/shared';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import {
  addMember,
  boot,
  cleanUp,
  connect,
  createBoard,
  createUser,
  emit,
  REALTIME_1,
  REALTIME_2,
  type Harness,
  type TestBoard,
  type TestSocket,
  type TestUser,
} from './harness';

/**
 * Cross-replica delivery: the property the project is actually judged on.
 *
 * **Two gateway processes, not one, and that is the whole test.** With a single
 * process every socket shares one in-memory adapter, so a broadcast reaches every
 * client whether or not `@socket.io/redis-adapter` is wired at all -- the
 * assertion would pass with the adapter deleted. `scripts/integration.sh` starts
 * `apps/realtime/dist/main.js` twice, on 4100 and 4101, and this file puts one
 * client on each. The only path from one to the other is Redis pub/sub.
 *
 * It also covers the three things that are only observable across a socket:
 * the ack is typed and carries `reconciled`, a `FORBIDDEN` reaches the client
 * that caused it and nobody else, and a REST write made with no socket open still
 * reaches everyone with the board open (the `@socket.io/redis-emitter` path,
 * which has no other test).
 */
describe('two gateways, one board', () => {
  let harness: Harness;
  let owner: TestUser;
  let editor: TestUser;
  let viewer: TestUser;
  let board: TestBoard;
  let first: TestSocket;
  let second: TestSocket;

  beforeAll(async () => {
    harness = await boot();
    owner = await createUser(harness.prisma, 'owner');
    editor = await createUser(harness.prisma, 'editor');
    viewer = await createUser(harness.prisma, 'viewer');
    board = await createBoard(harness, owner, ['Todo', 'Doing']);
    await addMember(harness, board, editor, 'EDITOR');
    await addMember(harness, board, viewer, 'VIEWER');

    first = await connect(REALTIME_1, owner, board.id);
    second = await connect(REALTIME_2, editor, board.id);
  });

  afterAll(async () => {
    first?.close();
    second?.close();
    await cleanUp(harness.prisma, [owner, editor, viewer]);
    await harness.close();
  });

  it('delivers a move made on :4100 to a client on :4101', async () => {
    const created = await emit(first.socket, 'card.create', {
      boardId: board.id,
      listId: board.lists[0]!.id,
      title: 'Crosses the adapter',
    });
    expect(created.ok, JSON.stringify(created)).toBe(true);
    const card = (created.data as { card: { id: string; version: number } }).card;

    // Listen before emitting. Subscribing after the write is a race the test
    // would lose intermittently and blame on the adapter.
    const delivered = second.next<CardMoved>(SERVER_EVENTS.cardMoved);

    const moved = await emit(first.socket, 'card.move', {
      boardId: board.id,
      cardId: card.id,
      expectedVersion: card.version,
      toListId: board.lists[1]!.id,
      afterCardId: null,
      beforeCardId: null,
    });
    expect(moved.ok, JSON.stringify(moved)).toBe(true);

    const event = await delivered;
    expect(event.cardId).toBe(card.id);
    expect(event.fromListId).toBe(board.lists[0]!.id);
    expect(event.toListId).toBe(board.lists[1]!.id);
    // The authoritative position, generated by the server. The client asked for
    // neighbours and never for a key.
    expect(event.position).toMatch(/^[a-zA-Z0-9]+$/);
    expect(event.version).toBe(card.version + 1);
  });

  it('carries `reconciled` on the ack, where the broadcast has no room for it', async () => {
    // `reconciled` tells the client that ITS optimistic placement was computed
    // against a stale neighbour pair. That is a fact about one client, so it
    // belongs in the ack rather than in an event everybody receives.
    const created = await emit(first.socket, 'card.create', {
      boardId: board.id,
      listId: board.lists[0]!.id,
      title: 'Reconcile me',
    });
    const card = (created.data as { card: { id: string; version: number } }).card;

    const moved = await emit(first.socket, 'card.move', {
      boardId: board.id,
      cardId: card.id,
      expectedVersion: card.version,
      toListId: board.lists[1]!.id,
      afterCardId: null,
      beforeCardId: null,
    });

    expect(moved.ok).toBe(true);
    expect(moved.data).toHaveProperty('reconciled');
  });

  it('refuses a viewer’s move, and tells only the viewer', async () => {
    const created = await emit(first.socket, 'card.create', {
      boardId: board.id,
      listId: board.lists[0]!.id,
      title: 'Viewers may not move this',
    });
    const card = (created.data as { card: { id: string; version: number } }).card;

    const watcher = await connect(REALTIME_2, viewer, board.id);
    try {
      const refused = await emit(watcher.socket, 'card.move', {
        boardId: board.id,
        cardId: card.id,
        expectedVersion: card.version,
        toListId: board.lists[1]!.id,
        afterCardId: null,
        beforeCardId: null,
      });

      expect(refused.ok).toBe(false);
      // A typed code, not prose. `FORBIDDEN` drives an explanation in the client;
      // `STALE` would drive a refetch, and a client matching on message text
      // breaks the first time the message improves.
      expect(refused.error?.code).toBe('FORBIDDEN');

      // And the card did not move for anybody. A refusal that still wrote would
      // be the worst outcome available here.
      const board_ = await harness.http
        .get(`/boards/${board.id}`)
        .set('Authorization', owner.auth)
        .expect(200);
      const todo = (board_.body as Board).lists.find((list) => list.id === board.lists[0]!.id);
      expect(todo?.cards.map((entry) => entry.id)).toContain(card.id);
    } finally {
      watcher.close();
    }
  });

  it('delivers a REST write to every socket, through the Redis emitter', async () => {
    // The API runs no Socket.io server. A board rename happens on the boards
    // list, where nobody has a socket open, and it still has to reach everybody
    // who does -- via `@socket.io/redis-emitter` publishing onto the same channel
    // the adapter subscribes to. Nothing else in the suite exercises that path,
    // and its failure is silent: the rename succeeds and no one sees it.
    const renamed = second.next<{ boardId: string; name: string }>(SERVER_EVENTS.boardRenamed);

    await harness.http
      .patch(`/boards/${board.id}`)
      .set('Authorization', owner.auth)
      .send({ name: 'Renamed over REST' })
      .expect(200);

    const event = await renamed;
    expect(event).toEqual({ boardId: board.id, name: 'Renamed over REST' });
  });

  it('delivers the activity line that a socket write produced', async () => {
    // The `onActivity` hook on `PrismaBoardRepository` fires only after the
    // transaction commits. A per-append hook would announce `moveCard`'s losing
    // retry attempt as well as the winning one, and every reader would see the
    // card move twice.
    const appended = second.next<{ activity: { type: string; subject: string } }>(
      SERVER_EVENTS.activityAppended,
    );

    await emit(first.socket, 'card.create', {
      boardId: board.id,
      listId: board.lists[0]!.id,
      title: 'Writes an activity line',
    });

    const event = await appended;
    expect(event.activity.type).toBe('card.created');
    expect(event.activity.subject).toBe('Writes an activity line');
  });

  it('refuses a handshake with no token', async () => {
    // The gateway must never let an unauthenticated socket reach a handler, not
    // even to be refused there.
    const { io } = await import('socket.io-client');
    const socket = io(REALTIME_1, { transports: ['websocket'], reconnection: false });

    const error = await new Promise<Error>((resolve) => {
      socket.on('connect_error', resolve);
    });
    socket.close();

    expect(error.message).toMatch(/token/i);
  });
});
